name: Solace Interface Deployment - Final Version

events:
  workflow_dispatch:

    type: workflow_dispatch

  jobs:
    - name: Deploy Interface
      run: python3 -m interface_app.py

    - name: Start Server
      run: python -m interface_app.py